In [2]:
from scipy.stats import ttest_1samp
import numpy as np
import pandas as pd

In [3]:
df=pd.read_csv('videos.csv',usecols=['likes'])

In [4]:
print(df)

        likes
0      320053
1      185853
2      576597
3       24975
4       96666
5       34507
6        9985
7       74062
8       69687
9       29943
10      34485
11      28050
12       8085
13       9215
14      14740
15      18936
16      14870
17      65749
18      23945
19       7941
20      66420
21       1521
22       2921
23      21817
24       3498
25       6126
26     384920
27      16258
28      65730
29      15424
...       ...
7968      514
7969  1075133
7970    11262
7971      116
7972      217
7973     3048
7974    73813
7975     8694
7976      936
7977     5728
7978       93
7979     6401
7980     2139
7981      500
7982     8700
7983    21909
7984    17145
7985    67484
7986     2434
7987      189
7988   132302
7989      376
7990      305
7991    18242
7992     6688
7993    14362
7994     1265
7995     7088
7996     2148
7997     1574

[7998 rows x 1 columns]


In [5]:
df.describe()

likes
count  7.998000e+03
mean   3.450900e+04
std    9.135465e+04
min    0.000000e+00
25%    1.901500e+03
50%    8.649500e+03
75%    3.022050e+04
max    2.010366e+06

In [8]:
dislikes=np.mean(df)
print(dislikes)

likes    34508.996624
dtype: float64


In [12]:
test,pval=ttest_1samp(df,25)
print("mean dislikes",pval)
if pval<0.05:
 print("we are rejecting null hypothesis")
else:
 print("we are accepting null hypothesis")

mean dislikes [1.14137458e-233]
we are rejecting null hypothesis


In [21]:
import pandas as pd
import pandas.util.testing as tm
from scipy import stats
from statsmodels.stats import weightstats as stests

In [18]:
ztest,pval=stests.ztest(df['likes'],x2=None,value=2)
print(float(pval))
if pval<0.05:
    print("reject null hypothesis")
else:
     print("accept null hypothesis")

3.802713299067203e-250
reject null hypothesis


In [7]:
import pandas as pd
df_anova=pd.read_csv('videos.csv')
df_anova=df_anova[['likes','dislikes']]
grps=pd.unique(df_anova.dislikes.values)
d_data={grp:df_anova['likes'][df_anova.dislikes==grp]for grp in grps}
print(d_data)

{5931: 0       320053
5840      2170
Name: likes, dtype: int64, 26679: 1    185853
Name: likes, dtype: int64, 39774: 2    576597
Name: likes, dtype: int64, 4542: 3    24975
Name: likes, dtype: int64, 568: 4       96666
1275     7163
5120    14271
7165      929
Name: likes, dtype: int64, 544: 5       34507
453      7703
1196    83346
5517    22022
Name: likes, dtype: int64, 297: 6        9985
82      20164
96       3391
480      9801
2036    11872
2257    16034
Name: likes, dtype: int64, 2180: 7      74062
64    104899
Name: likes, dtype: int64, 678: 8        69687
219      40496
715      43748
1251     17129
1846       337
4343     37292
5709      9913
6833    115579
7596     51387
Name: likes, dtype: int64, 878: 9       29943
1350    10270
4642    21268
Name: likes, dtype: int64, 726: 10      34485
1601    20232
6694    12623
7423     4952
Name: likes, dtype: int64, 405: 11      28050
1211    20793
5695    16628
Name: likes, dtype: int64, 303: 12       8085
341      3442
953     18879

In [10]:
import itertools
v=dict(itertools.islice(d_data.items(),5))
print(v)

{5931: 0       320053
5840      2170
Name: likes, dtype: int64, 26679: 1    185853
Name: likes, dtype: int64, 39774: 2    576597
Name: likes, dtype: int64, 4542: 3    24975
Name: likes, dtype: int64, 568: 4       96666
1275     7163
5120    14271
7165      929
Name: likes, dtype: int64}


In [44]:
df_chi=pd.read_csv('videos.csv')
contingency_table=pd.crosstab(df_chi["likes"],df_chi["dislikes"])
print('contingency_table :-\n',contingency_table)

contingency_table :-
 dislikes  0       1       2       3       4       5       6       7       \
likes                                                                      
0             84       0       0       0       1       0       0       0   
1              3       2       2       1       0       0       0       0   
2              5       0       0       0       0       0       0       0   
3              6       0       0       0       0       0       0       0   
4              3       1       0       0       0       0       0       0   
5              3       2       0       0       1       0       1       0   
6              2       1       0       0       0       0       0       0   
7              1       1       0       0       0       0       0       0   
8              3       0       0       0       0       0       0       0   
9              4       1       0       0       0       0       0       0   
10             3       0       1       0       0       0       0  

In [19]:
#Observed Values
Observed_Values=contigency_table.values
print("Observed Values :-\n",Observed_Values)

Observed Values :-
 [[84  0  0 ...  0  0  0]
 [ 3  2  2 ...  0  0  0]
 [ 5  0  0 ...  0  0  0]
 ...
 [ 0  0  0 ...  0  0  0]
 [ 0  0  0 ...  0  0  0]
 [ 0  0  0 ...  0  0  0]]


In [27]:
#Degree of Freedom
no_of_rows=len(contigency_table.iloc[0:2,0])
no_of_columns=len(contigency_table.iloc[0,0:2])
ddof=(no_of_rows-1)*(no_of_columns-1)
print("Degree of Freedom:",ddof)

Degree of Freedom: 1


In [49]:
#chi_square_statistic
alpha=0.05
from scipy.stats import chi2
chi_square=sum([(o-e)**2./e for o,e in zip(Observed_Values,Expected_Values)])
chi_square_statistic=chi_square[0]+chi_square[1]
print("chi_square statistic:",chi_square_statistic)

chi_square statistic: 8391.305041377904


In [45]:
#Expected Values
from scipy.stats import chi2
b=stats.chi2_contingency(contingency_table)
Expected_Values=b[3]
print("Expected Values :-\n",Expected_Values)




Expected Values :-
 [[2.26369092e+00 5.63265816e-01 6.16404101e-01 ... 1.06276569e-02
  1.06276569e-02 1.06276569e-02]
 [2.13053263e-01 5.30132533e-02 5.80145036e-02 ... 1.00025006e-03
  1.00025006e-03 1.00025006e-03]
 [2.66316579e-01 6.62665666e-02 7.25181295e-02 ... 1.25031258e-03
  1.25031258e-03 1.25031258e-03]
 ...
 [2.66316579e-02 6.62665666e-03 7.25181295e-03 ... 1.25031258e-04
  1.25031258e-04 1.25031258e-04]
 [2.66316579e-02 6.62665666e-03 7.25181295e-03 ... 1.25031258e-04
  1.25031258e-04 1.25031258e-04]
 [2.66316579e-02 6.62665666e-03 7.25181295e-03 ... 1.25031258e-04
  1.25031258e-04 1.25031258e-04]]


In [50]:
#critical value
critical_value=chi2.ppf(q=1-alpha,df=ddof)
print("critical_value:",critical_value)

critical_value: 3.841458820694124


In [51]:
#p-value
p_value=1-chi2.cdf(x=chi_square_statistic,df=ddof)
print("p-value",p_value)  
print("Significance level:",alpha)
print("Degree of Freedom:",ddof)
print("chi-square statistic",chi_square_statistic)
print("critical_value:",critical_value)
print("p-value:",p_value)

p-value 0.0
Significance level: 0.05
Degree of Freedom: 1
chi-square statistic 8391.305041377904
critical_value: 3.841458820694124
p-value: 0.0


In [53]:
if chi_square_statistic>=critical_value:
 print("Reject HO,There is a relationship between 2 categorical variables")
else:
 print("Retain HO,There is no relationship between 2 categorical variables")
if p_value<=alpha:
 print("Reject HO,There is a relationship between 2 categorical variables")
else:
 print("Retain HO,There is no relationship between 2 categorical variables")
    

    

Reject HO,There is a relationship between 2 categorical variables
Reject HO,There is a relationship between 2 categorical variables
